/*
 * This Java source file was generated by the Gradle 'init' task.
 */








//Help from chatgbt

package bitmap.transformer;


import java.io.IOException;

public class App {
    public static void main(String[] args) {
        if (args.length < 3) {
            System.err.println("Error");
            return;
        }

        String inputPath = "src/main/resources/baldy-8bit.bmp";
        String outputPath = "src/main/resources/output.bmp";
        String transformMethod = args[2];

        try {
            Bitmap bitmap = new Bitmap(inputPath);
            bitmap.applyTransform(transformMethod);
            bitmap.writeToFile(outputPath);
            System.out.println("Transform applied: " + outputPath);
        } catch (IOException e) {
            System.err.println("Error");
        }
    }
}


